name: 'build'
on: # rebuild any PRs and main branch changes
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v4

      - name: Read version from file and set as env var
        id: set_version
        run: echo "TAG_VERSION=$(cat .devcontainer/platform_version.txt)" >> $GITHUB_ENV

      - name: Display version
        run: echo "Version is $TAG_VERSION"

      - name: Set up QEMU for multi-architecture builds
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker buildx for multi-architecture builds
        uses: docker/setup-buildx-action@v3
        with:
          use: true

      - name: Login to dockerhub Container Registry
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Login to nexus Container Registry
        uses: docker/login-action@v3
        with:
          registry: registry.weslyg.ru
          username: ${{ secrets.NEXUS_USERNAME }}
          password: ${{ secrets.NEXUS_PASSWORD }}

      - name: Install Node.js and npm
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install devcontainers cli
        run: npm i -g @devcontainers/cli

      - name: Build nexus image and push
        run: devcontainer build --workspace-folder . --image-name registry.weslyg.ru/nodejs-infra:$TAG_VERSION --platform linux/amd64,linux/arm64 --push
      
      - name: Build dockerhub and push
        run: devcontainer build --workspace-folder . --image-name weslyg/nodejs-infra:$TAG_VERSION --platform linux/amd64,linux/arm64 --push
